version: '3.2'
services:
  db:
    image: postgres
    container_name: email_verification_db
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: banco123
        POSTGRES_DB: email_verification
