#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: banco123
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: email_verification

#Server
SERVER_PORT: 7800
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: "<your email id>" # <--- Put your email id here
EMAIL_PASSWORD: "<your email password>" # <--- Put your email password here
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}



